---
os: linux
dist: bionic
language: python

branches:
  only:
    - master

env:
  global:
    - secure: "ntp3BBxM1ai7A3lB3Kz1/XIt9Gzh4AlIxp+2gQkLs3A2ZGvUzch2d9yioLYWCIEPKEKcc7AyxuqOgELfD5F4dGQgG+2SRONui/m6NMecr0Rus3zKbAIvu+p9l9POcrTCS78c4GX+msUUdEUc43nb0wmBa32vphCdzHpuay87zjmRN/nUmnMqJvOXfZr2xMBqrjs8pkk86cIXXOnqiwM91aH8z9cwnRp/DUmbgBtcC3nT9JOIfqCJvWe7yfN2NvCxC0lV60wChKm6YDo14A7cPWbDmE6Gbc4/AnRFMHN8xvZ+Iagbthu9SeF4yKVcW6Bqd/v8qEdC+sF5L2hFn3uxw0hWpb9K5gAp6TseX1t6AkUblDirEt2LAUYEKaWW+evU3iOdFEUCI72FfcgdqlGgB0AtY5r5XAED7QP20qdm1rdRRV7U5gtLAfhPOTyo5m4/kxjMHj2vg0YYwD+Pjwq/PVmP902BhQ/6aMpeoVebzaOSmSXpmeUt4rWlN+vAlgxoipBFv0jIZWg+HWJRVDtbmnKWRpAV97FOZZzS2e4cCy93TeoVglegJoODNu13Jdn4C/3s+XwWepu8B4T8Ndmnt9CrtCRvfV1wNiCiGeT25RzPalSKc/LpeAkXz77GLz4fnmCnylrsLWcv4CGlbtzwDBWadwoP0jQyuDK0DFtiSyk=" # contains GH_TOKEN
  jobs:
    - MOLECULE_DISTRO_BOX="generic/ubuntu1604"
    - MOLECULE_DISTRO_BOX="generic/centos7"

cache: # Cache the big Vagrant boxes
  directories:
  - /home/travis/.vagrant.d/boxes

install:
  - sudo add-apt-repository universe && sudo apt update
  - export VAGRANT_VERSION=2.2.10
  - wget "https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb"
  - sudo dpkg -i "vagrant_${VAGRANT_VERSION}_x86_64.deb"
  - vagrant --version  # Vagrant correctly installed?
  - sudo apt install qemu-kvm qemu-utils libvirt-bin libvirt0 libvirt-dev
  - vagrant plugin install vagrant-libvirt
  - pip install molecule molecule-vagrant python-vagrant ansible-lint
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

jobs:
  allow_failures:
    - env: MOLECULE_DISTRO_BOX="generic/ubuntu1604"

script:
  - molecule --version
  - ansible --version
  - molecule test
after_success:
  - |
    if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
      git config --global user.email "builds@travis-ci.com"
      git config --global user.name "Travis CI"
      export GIT_TAG=$(date +"%y").$(date +"%m" | sed 's/^0*//').$TRAVIS_BUILD_NUMBER
      git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      git push -q "https://${GH_TOKEN}@github.com/New-Edge-Engineering/ansible-packages" --tags
    fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master