---
- name: restart Debian networking
  service:
    name: networking
    state: restarted  # Restart may change the IP Address causing Ansible to hang.

- name: restart RedHat networking
  service:
    name: network
    state: restarted
