---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: find dhclient
      lineinfile: 
        dest: "/etc/dhcp/dhclient.conf"
        regexp: "^supersede domain-name-servers {{ networking_domain_name_server }};$"
        state: absent
      become: true
      check_mode: true
      register: dhclient_presence
    - name: find networking_domain_name_server
      lineinfile: 
        dest: "/etc/sysconfig/network-scripts/ifcfg-eth0"
        regexp: "^DNS1={{ networking_domain_name_server }}$"
        state: absent
      check_mode: true
      register: networking_domain_name_server_presence
    - name: find resolvconf
      lineinfile: 
        dest: "/etc/resolvconf/resolv.conf.d/base"
        regexp: "^nameserver {{ networking_domain_name_server }}$"
        state: absent
      check_mode: true
      register: resolvconf_presence
    - name: verification
      assert:
        that:
          - dhclient_presence.found == 1
          - (networking_domain_name_server_presence|default({'found':0})).found|default(0) == 1 or (resolvconf_presence|default({'found':0})).found|default(0) == 1
