---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: find dhclient
      lineinfile: 
        dest: "/etc/dhcp/dhclient.conf"
        regexp: "^supersede domain-name-servers {{ networking_domain_name_server }};$"
        state: absent
      become: true
      check_mode: true
      register: dhclient_presence
    - name: find resolvconf
      lineinfile: 
        dest: "/etc/resolvconf/resolv.conf.d/base"
        regexp: "^nameserver {{ networking_domain_name_server }}$"
        state: absent
      check_mode: true
      register: resolvconf_presence
    - name: verifiction
      assert:
        that:
          - dhclient_presence.found == 1
          - resolvconf_presence.found == 1
